version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
    binary: fizzy-md

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: zainfathoni
    name: fizzy-md
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
  header: |
    ## What's Changed

    fizzy-md {{ .Version }} is here! 🎉

  footer: |
    **Full Changelog**: https://github.com/zainfathoni/fizzy-md/compare/{{ .PreviousTag }}...{{ .Tag }}

brews:
  - repository:
      owner: zainfathoni
      name: homebrew-fizzy
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: https://github.com/zainfathoni/fizzy-md
    description: Transparent Markdown→HTML wrapper for Fizzy CLI
    license: MIT
    test: |
      system "#{bin}/fizzy-md --version"
    install: |
      bin.install "fizzy-md"
